apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-pv-claim
  labels:
    app: httpd-frontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    app: httpd-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-frontend
  strategy:
    type: RollingUpdate
    rollingParams:
      updatePeriodSeconds: 1 
      intervalSeconds: 1 
      timeoutSeconds: 120 
      maxSurge: "20%" 
      maxUnavailable: "10%" 
      pre: {} 
      post: {}
  template:
    metadata:
      labels:
        app: httpd-frontend
    spec:
      containers:
      - image: registry.redhat.io/rhel8/httpd-24
        imagePullPolicy: Always
        name: httpd-rhel7
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 8443
          name: https-port
        volumeMounts:
        - name: httpd-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: httpd-persistent-storage
        persistentVolumeClaim:
          claimName: httpd-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: http-port
  labels:
    app: httpd-frontend
spec:
  ports:
    - port: 8080
      name: http-port
      protocol: TCP
      targetPort: 8080
  selector:
    app: httpd-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: https-port
  labels:
    app: httpd-frontend
spec:
  ports:
    - port: 8443
      name: https-port
      protocol: TCP
      targetPort: 8443
  selector:
    app: httpd-frontend
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: httpd-frontend
  managedFields:
  name: http-port
spec:
  port:
    targetPort: http-port
  to:
    kind: Service
    name: http-port
    weight: 100
