apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-httpd
  namespace: openshift-gitops
spec:
  destination:
    namespace: demo-httpd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: https://github.com/rdiazgav/demo-httpd.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
